name: sonarr

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.19
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Rome
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HDD_VOLUMES_BASEDIR}/sonarr/config:/config
      - ${ARRSTACK_BASE_PATH}:/data
    # ports:
    #   - "8989:8989"
    restart: unless-stopped
    networks:
      - pangolin-private-proxy
    labels:
      - pangolin.proxy-resources.sonarr.name=Sonarr
      - pangolin.proxy-resources.sonarr.full-domain=sonarr.${PRIVATE_DOMAIN}
      - pangolin.proxy-resources.sonarr.protocol=http
      - pangolin.proxy-resources.sonarr.auth.sso-enabled=false
      - pangolin.proxy-resources.sonarr.targets[0].method=http
      - pangolin.proxy-resources.sonarr.targets[0].port=8989

networks:
  pangolin-private-proxy:
    external: true